create table if not exists public.candidate_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  full_name text not null,
  email text not null,
  phone text not null,
  vocation text not null,
  province text not null,
  country text not null,
  experience_years integer not null default 0,
  availability text not null,
  license boolean not null default false,
  license_country text,
  reference_letter_url text,
  message text,
  status text not null default 'pending'
);

create unique index if not exists candidate_applications_email_idx
  on public.candidate_applications (email);
